### ISSUE TITLE
Subtlety: It is important and helpful to apply consistent code formatting in your CSS.

### ISSUE THREAD

**Issue by josephtkim** [ayrdawg/teacozy-project#5]
There were certain lines in the CSS which had inconsistent code indentation. It is always a good idea to apply formatting consistently throughout the code to improve the code readability. For example, the body section formatting might be changed to:

```css
body{
  height: 2000px;
  font-size: 22px;
  font-family: helvetica;
  color: seashell;
  background-color: black;
  opacity: 0.9;
  margin: 0px;
}
```
